runs:
  using: "Composite"

  steps:
    - name: Create configs/firebase.json
      env:
        DECODED_BASE64: ${{ inputs.COMMON_FIREBASE_BASE64 }}
      run: |
        mkdir -p ./configs && echo $DECODED_BASE64 | base64 --decode > ./configs/firebase.json
      shell: bash
