runs:
  using: "Composite"

  steps:
    - name: Create configs/firebase.json
      env:
        DECODED_BASE64: ${{ inputs.COMMON_FIREBASE_BASE64 }}
      run: |
        mkdir -p ${{ env.target }}/configs && echo $DECODED_BASE64 | base64 --decode > ${{ env.target }}/configs/firebase.json
      shell: bash
